version_requirement = ">=1.3.0"

[server]
domain = "smtp.user.tax"

[server.interfaces]
addr = ["62.171.170.189:25","[2a02:c207:2098:9386::1]:25"]
addr_submission = ["62.171.170.189:587","[2a02:c207:2098:9386::1]:587"]
addr_submissions = ["62.171.170.189:465","[2a02:c207:2098:9386::1]:465"]

[server.tls]
security_level = "Encrypt"
#security_level = "May"
protocol_version = ["TLSv1.3"]
certificate = "/mnt/www/.acme.sh/user.tax/fullchain.cer"
private_key = "/mnt/www/.acme.sh/user.tax/user.tax.key"
preempt_cipherlist = false
handshake_timeout = "6000ms"

[server.virtual."iuser.in".tls]
protocol_version = ["TLSv1.3"]
certificate = "/mnt/www/.acme.sh/iuser.in/fullchain.cer"
private_key = "/mnt/www/.acme.sh/iuser.in/iuser.in.key"

[server.virtual."iuser.in".dkim]
private_key = "/root/user/key/smtp/iuser.in/1hg.pem"

[server.virtual."user.tax".tls]
protocol_version = ["TLSv1.3"]
certificate = "/mnt/www/.acme.sh/user.tax/fullchain.cer"
private_key = "/mnt/www/.acme.sh/user.tax/user.tax.key"

[server.virtual."user.tax".dkim]
private_key = "/root/user/key/smtp/user.tax/1hg.pem"

[server.smtp.auth]
must_be_authenticated = true
enable_dangerous_mechanism_in_clair = false

[app.vsl]
filepath = "/etc/vsmtp/main.vsl"

[server.logs]
filepath = "/var/log/vsmtp"
level = [ "warn" ]

